import Head from 'next/head'
import { useRouter } from 'next/router'

export default function Home() {

  const router = useRouter()
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex justify-between m-5 text-2xl'>
        <h2>BOOFE</h2>
        <button
          className="bg-lime-400 p-3 rounded-md drop-shadow text-white"
          onClick={() => router.push('/auth/login')}
        >Sign Up</button>
      </div>

    </div>
  )
}
